package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

/**
 * Boletotren generated by hbm2java
 */
public class Boletotren implements java.io.Serializable {

	private Integer idBoletoTren;
	private Estaciontren estaciontrenByIdEstacionBajada;
	private Estaciontren estaciontrenByIdEstacionSubida;
	private Tarifatren tarifatren;
	private Viaje viaje;
	private float precioFinal;
	private String descripcion;

	public Boletotren() {
	}

	public Boletotren(Estaciontren estaciontrenByIdEstacionSubida, Tarifatren tarifatren, Viaje viaje,
			float precioFinal, String descripcion) {
		this.estaciontrenByIdEstacionSubida = estaciontrenByIdEstacionSubida;
		this.tarifatren = tarifatren;
		this.viaje = viaje;
		this.precioFinal = precioFinal;
		this.descripcion = descripcion;
	}

	public Boletotren(Estaciontren estaciontrenByIdEstacionBajada, Estaciontren estaciontrenByIdEstacionSubida,
			Tarifatren tarifatren, Viaje viaje, float precioFinal, String descripcion) {
		this.estaciontrenByIdEstacionBajada = estaciontrenByIdEstacionBajada;
		this.estaciontrenByIdEstacionSubida = estaciontrenByIdEstacionSubida;
		this.tarifatren = tarifatren;
		this.viaje = viaje;
		this.precioFinal = precioFinal;
		this.descripcion = descripcion;
	}

	public Integer getIdBoletoTren() {
		return this.idBoletoTren;
	}

	public void setIdBoletoTren(Integer idBoletoTren) {
		this.idBoletoTren = idBoletoTren;
	}

	public Estaciontren getEstaciontrenByIdEstacionBajada() {
		return this.estaciontrenByIdEstacionBajada;
	}

	public void setEstaciontrenByIdEstacionBajada(Estaciontren estaciontrenByIdEstacionBajada) {
		this.estaciontrenByIdEstacionBajada = estaciontrenByIdEstacionBajada;
	}

	public Estaciontren getEstaciontrenByIdEstacionSubida() {
		return this.estaciontrenByIdEstacionSubida;
	}

	public void setEstaciontrenByIdEstacionSubida(Estaciontren estaciontrenByIdEstacionSubida) {
		this.estaciontrenByIdEstacionSubida = estaciontrenByIdEstacionSubida;
	}

	public Tarifatren getTarifatren() {
		return this.tarifatren;
	}

	public void setTarifatren(Tarifatren tarifatren) {
		this.tarifatren = tarifatren;
	}

	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

	public float getPrecioFinal() {
		return this.precioFinal;
	}

	public void setPrecioFinal(float precioFinal) {
		this.precioFinal = precioFinal;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
