package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

/**
 * Boletosubte generated by hbm2java
 */
public class Boletosubte implements java.io.Serializable {

	private Integer idBoletoSubte;
	private Estacionsubte estacionsubte;
	private Tarifasubte tarifasubte;
	private Viaje viaje;
	private String descripcion;
	private float precio;

	public Boletosubte() {
	}

	public Boletosubte(Estacionsubte estacionsubte, Tarifasubte tarifasubte, Viaje viaje, String descripcion,
			float precio) {
		this.estacionsubte = estacionsubte;
		this.tarifasubte = tarifasubte;
		this.viaje = viaje;
		this.descripcion = descripcion;
		this.precio = precio;
	}

	public Integer getIdBoletoSubte() {
		return this.idBoletoSubte;
	}

	public void setIdBoletoSubte(Integer idBoletoSubte) {
		this.idBoletoSubte = idBoletoSubte;
	}

	public Estacionsubte getEstacionsubte() {
		return this.estacionsubte;
	}

	public void setEstacionsubte(Estacionsubte estacionsubte) {
		this.estacionsubte = estacionsubte;
	}

	public Tarifasubte getTarifasubte() {
		return this.tarifasubte;
	}

	public void setTarifasubte(Tarifasubte tarifasubte) {
		this.tarifasubte = tarifasubte;
	}

	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

}
