package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Descuento generated by hbm2java
 */
public class Descuento implements java.io.Serializable {

	private Integer idDescuento;
	private String descripcion;
	private float porcentaje;
	private Set usuarios = new HashSet(0);

	public Descuento() {
	}

	public Descuento(String descripcion, float porcentaje) {
		this.descripcion = descripcion;
		this.porcentaje = porcentaje;
	}

	public Descuento(String descripcion, float porcentaje, Set usuarios) {
		this.descripcion = descripcion;
		this.porcentaje = porcentaje;
		this.usuarios = usuarios;
	}

	public Integer getIdDescuento() {
		return this.idDescuento;
	}

	public void setIdDescuento(Integer idDescuento) {
		this.idDescuento = idDescuento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(float porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
