package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Lineacolectivo generated by hbm2java
 */
public class Lineacolectivo implements java.io.Serializable {

	private Integer idLineaColectivo;
	private String nombre;
	private Set boletocolectivos = new HashSet(0);

	public Lineacolectivo() {
	}

	public Lineacolectivo(String nombre) {
		this.nombre = nombre;
	}

	public Lineacolectivo(String nombre, Set boletocolectivos) {
		this.nombre = nombre;
		this.boletocolectivos = boletocolectivos;
	}

	public Integer getIdLineaColectivo() {
		return this.idLineaColectivo;
	}

	public void setIdLineaColectivo(Integer idLineaColectivo) {
		this.idLineaColectivo = idLineaColectivo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getBoletocolectivos() {
		return this.boletocolectivos;
	}

	public void setBoletocolectivos(Set boletocolectivos) {
		this.boletocolectivos = boletocolectivos;
	}

}
