package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

	private Integer idMovimiento;
	private Usuario usuario;
	private String tipo;
	private Date fechaHora;
	private String medio;
	private String detalle;
	private String valor;

	public Movimiento() {
	}

	public Movimiento(Usuario usuario, String tipo, String valor) {
		this.usuario = usuario;
		this.tipo = tipo;
		this.valor = valor;
	}

	public Movimiento(Usuario usuario, String tipo, Date fechaHora, String medio, String detalle, String valor) {
		this.usuario = usuario;
		this.tipo = tipo;
		this.fechaHora = fechaHora;
		this.medio = medio;
		this.detalle = detalle;
		this.valor = valor;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	public String getMedio() {
		return this.medio;
	}

	public void setMedio(String medio) {
		this.medio = medio;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
