package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Ramaltren generated by hbm2java
 */
public class Ramaltren implements java.io.Serializable {

	private Integer idRamalTren;
	private Lineatren lineatren;
	private String nombre;
	private Set ramalTieneEstacions = new HashSet(0);

	public Ramaltren() {
	}

	public Ramaltren(Lineatren lineatren, String nombre) {
		this.lineatren = lineatren;
		this.nombre = nombre;
	}

	public Ramaltren(Lineatren lineatren, String nombre, Set ramalTieneEstacions) {
		this.lineatren = lineatren;
		this.nombre = nombre;
		this.ramalTieneEstacions = ramalTieneEstacions;
	}

	public Integer getIdRamalTren() {
		return this.idRamalTren;
	}

	public void setIdRamalTren(Integer idRamalTren) {
		this.idRamalTren = idRamalTren;
	}

	public Lineatren getLineatren() {
		return this.lineatren;
	}

	public void setLineatren(Lineatren lineatren) {
		this.lineatren = lineatren;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getRamalTieneEstacions() {
		return this.ramalTieneEstacions;
	}

	public void setRamalTieneEstacions(Set ramalTieneEstacions) {
		this.ramalTieneEstacions = ramalTieneEstacions;
	}

}
