package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

/**
 * RamalTieneEstacion generated by hbm2java
 */
public class RamalTieneEstacion implements java.io.Serializable {

	private Integer idRamalEstacionTren;
	private Estaciontren estaciontren;
	private Ramaltren ramaltren;
	private int nroEstacion;

	public RamalTieneEstacion() {
	}

	public RamalTieneEstacion(Estaciontren estaciontren, Ramaltren ramaltren, int nroEstacion) {
		this.estaciontren = estaciontren;
		this.ramaltren = ramaltren;
		this.nroEstacion = nroEstacion;
	}

	public Integer getIdRamalEstacionTren() {
		return this.idRamalEstacionTren;
	}

	public void setIdRamalEstacionTren(Integer idRamalEstacionTren) {
		this.idRamalEstacionTren = idRamalEstacionTren;
	}

	public Estaciontren getEstaciontren() {
		return this.estaciontren;
	}

	public void setEstaciontren(Estaciontren estaciontren) {
		this.estaciontren = estaciontren;
	}

	public Ramaltren getRamaltren() {
		return this.ramaltren;
	}

	public void setRamaltren(Ramaltren ramaltren) {
		this.ramaltren = ramaltren;
	}

	public int getNroEstacion() {
		return this.nroEstacion;
	}

	public void setNroEstacion(int nroEstacion) {
		this.nroEstacion = nroEstacion;
	}

}
