package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Redsube generated by hbm2java
 */
public class Redsube implements java.io.Serializable {

	private Integer idRedSube;
	private String descuento;
	private String descripcion;
	private Set viajes = new HashSet(0);

	public Redsube() {
	}

	public Redsube(String descuento, String descripcion) {
		this.descuento = descuento;
		this.descripcion = descripcion;
	}

	public Redsube(String descuento, String descripcion, Set viajes) {
		this.descuento = descuento;
		this.descripcion = descripcion;
		this.viajes = viajes;
	}

	public Integer getIdRedSube() {
		return this.idRedSube;
	}

	public void setIdRedSube(Integer idRedSube) {
		this.idRedSube = idRedSube;
	}

	public String getDescuento() {
		return this.descuento;
	}

	public void setDescuento(String descuento) {
		this.descuento = descuento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getViajes() {
		return this.viajes;
	}

	public void setViajes(Set viajes) {
		this.viajes = viajes;
	}

}
