package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta implements java.io.Serializable {

	private Integer idTarjeta;
	private Usuario usuario;
	private String nroTarjeta;
	private float saldo;
	private boolean activa;
	private Set<Viaje> viajes = new HashSet<Viaje>(0);

	public Tarjeta() {
	}
	
	public Tarjeta(String nroTarjeta) {
		this.usuario = null;
		this.nroTarjeta = nroTarjeta;
		this.saldo = 0;
		this.activa = true;
	}
	
	public Tarjeta(Usuario usuario, String nroTarjeta, float saldo, boolean activa) {
		this.usuario = usuario;
		this.nroTarjeta = nroTarjeta;
		this.saldo = saldo;
		this.activa = activa;
	}

	public Tarjeta(Usuario usuario, String nroTarjeta, float saldo, boolean activa, Set viajes) {
		this.usuario = usuario;
		this.nroTarjeta = nroTarjeta;
		this.saldo = saldo;
		this.activa = activa;
		this.viajes = viajes;
	}

	public Integer getIdTarjeta() {
		return this.idTarjeta;
	}

	public void setIdTarjeta(Integer idTarjeta) {
		this.idTarjeta = idTarjeta;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNroTarjeta() {
		return this.nroTarjeta;
	}

	public void setNroTarjeta(String nroTarjeta) {
		this.nroTarjeta = nroTarjeta;
	}

	public float getSaldo() {
		return this.saldo;
	}

	public void setSaldo(float saldo) {
		this.saldo = saldo;
	}

	public boolean isActiva() {
		return this.activa;
	}

	public void setActiva(boolean activa) {
		this.activa = activa;
	}

	public Set<Viaje> getViajes() {
		return this.viajes;
	}

	public void setViajes(Set<Viaje> viajes) {
		this.viajes = viajes;
	}

	@Override
	public String toString() {
		return "Tarjeta [idTarjeta=" + idTarjeta + ", usuario=" + usuario + ", nroTarjeta=" + nroTarjeta + ", saldo="
				+ saldo + ", activa=" + activa + ", viajes=" + viajes + "]";
	}

	
	
}
