package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

/**
 * UsuarioTieneBeneficioId generated by hbm2java
 */
public class UsuarioTieneBeneficioId implements java.io.Serializable {

	private int idUsuario;
	private int idBeneficio;

	public UsuarioTieneBeneficioId() {
	}

	public UsuarioTieneBeneficioId(int idUsuario, int idBeneficio) {
		this.idUsuario = idUsuario;
		this.idBeneficio = idBeneficio;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdBeneficio() {
		return this.idBeneficio;
	}

	public void setIdBeneficio(int idBeneficio) {
		this.idBeneficio = idBeneficio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioTieneBeneficioId))
			return false;
		UsuarioTieneBeneficioId castOther = (UsuarioTieneBeneficioId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdBeneficio() == castOther.getIdBeneficio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdBeneficio();
		return result;
	}

}
