package datos;
// Generated 29/05/2018 01:28:13 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje implements java.io.Serializable {

	private Integer idViaje;
	private Redsube redsube;
	private Tarjeta tarjeta;
	private Date fechaHora;
	private Set boletocolectivos = new HashSet(0);
	private Set boletosubtes = new HashSet(0);
	private Set boletotrens = new HashSet(0);

	public Viaje() {
	}

	public Viaje(Redsube redsube, Tarjeta tarjeta, Date fechaHora) {
		this.redsube = redsube;
		this.tarjeta = tarjeta;
		this.fechaHora = fechaHora;
	}

	public Viaje(Redsube redsube, Tarjeta tarjeta, Date fechaHora, Set boletocolectivos, Set boletosubtes,
			Set boletotrens) {
		this.redsube = redsube;
		this.tarjeta = tarjeta;
		this.fechaHora = fechaHora;
		this.boletocolectivos = boletocolectivos;
		this.boletosubtes = boletosubtes;
		this.boletotrens = boletotrens;
	}

	public Integer getIdViaje() {
		return this.idViaje;
	}

	public void setIdViaje(Integer idViaje) {
		this.idViaje = idViaje;
	}

	public Redsube getRedsube() {
		return this.redsube;
	}

	public void setRedsube(Redsube redsube) {
		this.redsube = redsube;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	public Set getBoletocolectivos() {
		return this.boletocolectivos;
	}

	public void setBoletocolectivos(Set boletocolectivos) {
		this.boletocolectivos = boletocolectivos;
	}

	public Set getBoletosubtes() {
		return this.boletosubtes;
	}

	public void setBoletosubtes(Set boletosubtes) {
		this.boletosubtes = boletosubtes;
	}

	public Set getBoletotrens() {
		return this.boletotrens;
	}

	public void setBoletotrens(Set boletotrens) {
		this.boletotrens = boletotrens;
	}

}
